language: cpp
dist: bionic
os: linux

compiler: 
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
    - YCM_CHECKOUT=ycm-0.11
  jobs:
    - YARP_CHECKOUT=yarp-3.4
    - YARP_CHECKOUT=yarp-3.3

jobs:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=master
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=master

cache:
  directories: $CACHE_DIR    

addons:
  apt:
    packages:
    - libeigen3-dev # YARP API

install:
  #-- Install YCM
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YCM
    --repo-url https://github.com/robotology/ycm
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YCM_CHECKOUT}"

  #-- Install YARP
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

  #-- Install color-debug
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name COLOR_DEBUG
    --repo-url https://github.com/roboticslab-uc3m/color-debug
    --repo-checkout master

  #-- Install KDL
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name KDL
    --repo-url https://github.com/orocos/orocos_kinematics_dynamics
    --repo-checkout master
    --cmake-home-dir orocos_kdl
    --prepend-to-linker-path lib

  #-- Install kinematics-dynamics (for ICartesianControl)
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name ROBOTICSLAB_KINEMATICS_DYNAMICS
    --repo-url https://github.com/roboticslab-uc3m/kinematics-dynamics
    --repo-checkout master

  #-- Install yarp-devices (for testBasicCartesianControl and apps using proximity sensors)
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name ROBOTICSLAB_YARP_DEVICES
    --repo-url https://github.com/roboticslab-uc3m/yarp-devices
    --repo-checkout master
    --additional-export-paths "YARP_DATA_DIRS;share/roboticslab-yarp-devices"

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install"
  - make install
  - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
  - export YARP_DATA_DIRS=$PWD/install/share/roboticslab-kinematics-dynamics:$YARP_DATA_DIRS

script:
  - echo "No unit tests available"

after_success:
  - sudo make uninstall

notifications:
  email:
    recipients:
      - rasantos@it.uc3m.es
    on_success: change
    on_failure: always
